modLoader="javafml" #mandatory
loaderVersion="${forge_version_range}"
license="AGPL-3.0 WITH SimbaMC Proxy and SimbaMC Exceptions"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Simba"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="impactor"
mandatory=false
versionRange="[5.1.1, ]"
ordering="AFTER"
side="SERVER"
[[dependencies.${mod_id}]]
modId = "ftbchunks"
mandatory = false
versionRange = "[2001.3.0,)"
ordering = "AFTER"
side = "SERVER"
[[dependencies.${mod_id}]]
modId = "ftbteams"
mandatory = false
versionRange = "[2001.3.0,)"
ordering = "AFTER"
side = "SERVER"